### ISSUE TITLE
script don`t work((((

### ISSUE THREAD

**Issue by R4r3G0d** [gluckzhang/ctf-jwt-token#3]
give_me_the_flag.py dont work 
python3 give_me_the_flag.py -l http://localhost:8080/auth -u longz -p gogogo
INFO:root:successfully detect a jwt token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdXRoIjoxNjc3OTQ0MDI0NzI5LCJhZ2VudCI6Ik1vemlsbGEvNS4wIChXaW5kb3dzIE5UIDYuMSkgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzMxLjAuMTY1MC41NyBTYWZhcmkvNTM3LjM2Iiwicm9sZSI6InVzZXIiLCJpYXQiOjE2Nzc5NDQwMjV9.Qb8qLUktldySCezG8M7twByKJ9cg4tFV0jvAqt6rprc

INFO:root:jwt token header: {'typ': 'JWT', 'alg': 'HS256'}

Traceback (most recent call last):
  File "/mnt/c/users/vova_/desktop/ctf-jwt-token-master/give_me_the_flag.py", line 84, in <module>
    main()
  File "/mnt/c/users/vova_/desktop/ctf-jwt-token-master/give_me_the_flag.py", line 64, in main
    payload = jwt.decode(jwttoken, verify=False, algorithms=['HS256']) # decode the jwo token payload, the user role information is claimed in the payload
  File "/usr/lib/python3/dist-packages/jwt/api_jwt.py", line 119, in decode
    decoded = self.decode_complete(jwt, key, algorithms, options, **kwargs)
  File "/usr/lib/python3/dist-packages/jwt/api_jwt.py", line 90, in decode_complete
    decoded = api_jws.decode_complete(
  File "/usr/lib/python3/dist-packages/jwt/api_jws.py", line 152, in decode_complete
    self._verify_signature(signing_input, header, signature, key, algorithms)
  File "/usr/lib/python3/dist-packages/jwt/api_jws.py", line 239, in _verify_signature
    raise InvalidSignatureError("Signature verification failed")
jwt.exceptions.InvalidSignatureError: Signature verification failed

**Comment by YuanRuQian** [comment]
Hello @R4r3G0d, I have submitted [a pull request](https://github.com/gluckzhang/ctf-jwt-token/pull/4) to update the script. I believe the update should solve the issues you were experiencing. Please let me know if you encounter any further problems with the updated script. Thank you!

**Comment by gluckzhang** [comment]
Thanks @YuanRuQian for addressing the issue. Sorry about the late reply @R4r3G0d , I missed this issue last month. I think the merged PR fixes it. Feel free to reopen the issue if it does not help.
